MaxLogSize 0
Port 631
Listen /run/cups/cups.sock

Browsing Yes
BrowseLocalProtocols all
DefaultAuthType None

WebInterface Yes
ServerAlias *

<Location />
  Order allow,deny
  Allow from all
</Location>

<Location /admin>
  Order allow,deny
  Allow from all
</Location>

<Location /admin/conf>
  Order allow,deny
  Allow from all
</Location>

<Location /admin/log>
  Order allow,deny
  Allow from all
</Location>

<Policy default>
  JobPrivateAccess all
  JobPrivateValues all
  SubscriptionPrivateAccess all
  SubscriptionPrivateValues all

  <Limit All>
    Order allow,deny
    Allow from all
  </Limit>
</Policy>
