name: "Brother AirPrint"
version: "0.2.5"
slug: brother-airprint
description: "CUPS print server with original Brother HL-1110 driver and AirPrint support"
url: "https://github.com/craqs/ha-brother-airprint"
arch:
  - aarch64
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:printer
panel_title: Brother Printer
usb: true
host_network: true
ports:
  631/tcp: 631
ports_description:
  631/tcp: "CUPS web interface and IPP printing"
map:
  - config:rw
options:
  printer_name: "Brother_HL-1110"
  cups_admin_password: "print"
schema:
  printer_name: str
  cups_admin_password: password
